import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: "Ryan Smith's Portfolio",
  description: 'Generated by create next app',
}

export const sage_metadata: Metadata = {
  title: "Swing Sage",
  description: 'An all-in-one golf assistant',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
